// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChf9OEgEBotraLbILhOuAo1CI54oRkcws',
    appId: '1:180325216142:web:5dc896e1796d29a964bedf',
    messagingSenderId: '180325216142',
    projectId: 'operationsonfirebase',
    authDomain: 'operationsonfirebase.firebaseapp.com',
    storageBucket: 'operationsonfirebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU31scK4xCkHjDR_v-bszUqOQHvaa_RXA',
    appId: '1:180325216142:android:abb2007b7a64981a64bedf',
    messagingSenderId: '180325216142',
    projectId: 'operationsonfirebase',
    storageBucket: 'operationsonfirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCedUXL2gUDAUqri2c391L0L0vG5NczbqU',
    appId: '1:180325216142:ios:0f2b4340278abf3c64bedf',
    messagingSenderId: '180325216142',
    projectId: 'operationsonfirebase',
    storageBucket: 'operationsonfirebase.appspot.com',
    iosBundleId: 'com.example.operationsonfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCedUXL2gUDAUqri2c391L0L0vG5NczbqU',
    appId: '1:180325216142:ios:11fe27a670f2423064bedf',
    messagingSenderId: '180325216142',
    projectId: 'operationsonfirebase',
    storageBucket: 'operationsonfirebase.appspot.com',
    iosBundleId: 'com.example.operationsonfirebase.RunnerTests',
  );
}
